# Generated by Django 3.1.2 on 2020-10-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMAG_APP', '0002_auto_20201004_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
    ]
