# Generated by Django 3.1.2 on 2020-10-05 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EMAG_APP', '0005_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=755, unique=True)),
                ('event_category', models.CharField(max_length=400)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
