# Generated by Django 3.1.2 on 2020-10-08 08:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('EMAG_APP', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
