# Generated by Django 3.1.2 on 2020-10-08 11:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('EMAG_APP', '0007_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SG'),
        ),
    ]
