# Generated by Django 3.1.2 on 2020-10-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMAG_APP', '0010_auto_20201008_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
