# Generated by Django 3.1.2 on 2020-10-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMAG_APP', '0013_auto_20201008_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('Fest', 'Fest'), ('Workshop', 'Workshop'), ('Activity', 'Activity')], max_length=400),
        ),
    ]
