# Generated by Django 3.1.2 on 2020-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMAG_APP', '0014_auto_20201029_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_field',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
