# Generated by Django 3.1.2 on 2020-11-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMAG_APP', '0016_auto_20201118_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
        ),
    ]
